-- 코드를 입력하세요
SELECT DISTINCT USER_ID, NICKNAME, 
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, 
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', 
           SUBSTRING(TLNO, 4, 4), '-', 
           SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD AS b
JOIN USED_GOODS_USER AS u
ON b.WRITER_ID IN (
        SELECT b2.WRITER_ID
        FROM USED_GOODS_BOARD AS b2
        GROUP BY b2.WRITER_ID
        HAVING COUNT(*)>=3
    )
    AND b.WRITER_ID = u.USER_ID
ORDER BY b.WRITER_ID DESC;