-- 코드를 입력하세요
SELECT x.ANIMAL_ID, x.ANIMAL_TYPE, x.NAME
FROM (
    SELECT ins.ANIMAL_ID, ins.ANIMAL_TYPE, ins.NAME, SEX_UPON_INTAKE, SEX_UPON_OUTCOME
    FROM ANIMAL_INS AS ins
        JOIN ANIMAL_OUTS AS outs
        ON ins.ANIMAL_ID = outs.ANIMAL_ID
) AS x
WHERE SEX_UPON_INTAKE NOT LIKE 'Spayed%'
    AND SEX_UPON_INTAKE NOT LIKE 'Neutered%'
    AND (SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID ASC;