-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE*o.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS p
    JOIN 
    ( SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
     FROM FOOD_ORDER
     WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
     GROUP BY PRODUCT_ID
    ) AS o
    ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;