-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT AS p 
    JOIN DOCTOR AS d
    JOIN APPOINTMENT AS a
    ON p.PT_NO = a.PT_NO AND d.DR_ID = a.MDDR_ID
WHERE DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD;