-- 코드를 입력하세요
SELECT MONTH(h.START_DATE) AS MONTH, h.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
WHERE h.START_DATE >= '2022-08-01' AND h.START_DATE < '2022-11-01'
    AND h.CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
        GROUP BY CAR_ID
        HAVING COUNT(*)>=5
    )
GROUP BY MONTH(h.START_DATE), h.CAR_ID
ORDER BY MONTH(h.START_DATE) ASC, CAR_ID DESC;