-- 코드를 입력하세요
SELECT MONTH(c1.START_DATE) AS MONTH, c1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS c1
JOIN ( 
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE>='2022-08-01' AND START_DATE<'2022-11-01')
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
) AS c2 ON c1.CAR_ID = c2.CAR_ID
WHERE (c1.START_DATE>='2022-08-01' AND c1.START_DATE<'2022-11-01')
GROUP BY c1.CAR_ID, MONTH(c1.START_DATE)
ORDER BY MONTH(c1.START_DATE), c1.CAR_ID DESC;