-- 코드를 작성해주세요
SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO AS a 
JOIN FISH_NAME_INFO as b
ON a.FISH_TYPE = b.FISH_TYPE
WHERE (a.FISH_TYPE, a.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE);